"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Header from "@/app/header/page";
import Footer from "@/app/footer/page";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const nav = [
    "/home",
    "/userForm",
   
  ];
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
      {nav.includes(pathName) ? <Header /> : null}
        {children}
        {nav.includes(pathName) ? <Footer/> : null}
        </body>
    </html>
  );
}



